version: "3.7"
services: 
    congressoemchamas:
        image: pimentgabriel/congressoemchamas
        environment: 
            - PORT=8443
            - GOOGLE_NEWS_API_KEY=${GOOGLE_NEWS_API_KEY}
            - KEYSTORE_PATH=/cert.p12
            - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
            - JDBC_DATABASE_URL=jdbc:postgresql://${POSTGRES_URL}?user=${POSTGRES_USERNAME}&password=${POSTGRES_PASSWORD}
        ports:
            - "80:8443"
        volumes:
            - ${KEYSTORE_PATH}:/cert.p12