version: "3.7"
services: 
    congressoemchamas:
        image: pimentgabriel/congressoemchamas
        environment: 
            - PORT=80
            - GOOGLE_NEWS_API_KEY=${GOOGLE_NEWS_API_KEY}
            - JDBC_DATABASE_URL=jdbc:postgresql://${POSTGRES_URL}?user=${POSTGRES_USERNAME}&password=${POSTGRES_PASSWORD}
        ports:
            - "80:80"